//! In-memory external-documentation linkage over GridSeak nodes.
//!
//! # What this proves
//!
//! The compatibility under test is **survival of a linked document inside
//! a node's metadata** — nothing about any external wire format. A
//! documentation reference (a UUID pointing at an external doc —
//! Confluence / Notion / a GitHub `.md`) stored inside a node's
//! `properties` (the node's metadata bag) survives an FQN mutation that
//! churns the node's content-addressed `id`. Every survival assertion
//! inspects `node.properties` **directly** (see
//! [`assert_doc_link_in_metadata`]) so the proof is that the link
//! physically resides in the node metadata, not merely that a helper
//! returned it. It proves this for a single node and for a deeply nested
//! child inside a C4-style model of an online ordering / delivery system
//! (L1 System → L2 Container → L3 Component → L4 Code).
//!
//! NodeSync compatibility is explicitly **not** a goal here — that layer
//! is being rebuilt. The in-memory [`DocsStore`] is only a stand-in so a
//! surviving UUID can be shown to still resolve to a real doc.
//!
//! # Why the link survives
//!
//! `Node.id` is `SHA256(fqn [|| body])` — it is *engineered* to change
//! when the FQN or body changes (see `domain::node_id`). `Node.properties`
//! is a plain `HashMap` field that travels with the node value and is
//! **not keyed on `id`**. So a doc UUID parked in `properties` is carried
//! forward across a rename as long as the rename preserves `properties`.
//! The doc UUID is the durable anchor; the engine `id` is a fingerprint
//! that may churn underneath it.
//!
//! # The structural-edge contrast (load-bearing)
//!
//! `Contains` edges *are* keyed on node `id`. So the same FQN rename that
//! churns ids ALSO breaks containment edges. This test makes that explicit:
//! doc links never break, but id-keyed edges go stale and must be relinked
//! deterministically from the FQN anchor (`rebuild_contains_edges`). That
//! is the difference between anchor-keyed linkage (resilient) and
//! id-keyed linkage (needs a relink pass).
//!
//! # Scope boundary (honest about what this is NOT)
//!
//! This exercises the **in-memory carry-forward** guarantee on the domain
//! data structures. It does NOT exercise survival across a real re-scan:
//! on a fresh scan, nodes are rebuilt from source and `properties` is
//! regenerated by the classification pass, so an externally-injected doc
//! UUID would only reappear via a durable relink store keyed on the FQN
//! anchor. That persistence layer is out of scope here by design.

use std::collections::HashMap;

use graphengine_parsing::domain::{Edge, EdgeKind, Graph, Node, NodeKind, Provenance, Range};

// ---------------------------------------------------------------------------
// In-memory external documents store (the hardcoded "Docs Object")
// ---------------------------------------------------------------------------

/// One external documentation artifact: a database id, a stable UUID, a
/// URL to the doc anywhere on the web, and a free-form keyword tag array.
#[derive(Debug, Clone, PartialEq, Eq)]
struct DocObject {
    /// Surrogate database primary key.
    db_id: u64,
    /// Stable UUID (v4). This is the value parked inside a node's
    /// `properties` — the link anchor that must survive node mutation.
    doc_id: String,
    /// Link to the doc. Can point anywhere (Confluence, Notion, GitHub).
    url: String,
    /// Keyword tags so docs can be discovered by topic.
    tags: Vec<String>,
}

/// In-memory stand-in for the external documentation system. Keyed by
/// `doc_id` so a node holding a UUID can resolve back to the full doc.
#[derive(Debug, Default)]
struct DocsStore {
    by_doc_id: HashMap<String, DocObject>,
}

impl DocsStore {
    fn new() -> Self {
        Self::default()
    }

    fn insert(&mut self, doc: DocObject) {
        self.by_doc_id.insert(doc.doc_id.clone(), doc);
    }

    fn get(&self, doc_id: &str) -> Option<&DocObject> {
        self.by_doc_id.get(doc_id)
    }

    /// Resolve a set of doc UUIDs to their full objects, in the order
    /// given. A UUID that does not resolve is an unlinkage symptom and
    /// is surfaced as a `None` the caller can assert against.
    fn resolve_all<'a>(&'a self, doc_ids: &[String]) -> Vec<Option<&'a DocObject>> {
        doc_ids.iter().map(|id| self.get(id)).collect()
    }
}

// Hardcoded doc UUIDs (valid v4 format). Declared as consts so tests and
// the fixture builder reference the same literals.
const DOC_ARCH_OVERVIEW: &str = "f47ac10b-58cc-4372-a567-0e02b2c3d479";
const DOC_ORDERING_RUNBOOK: &str = "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d";
const DOC_CHECKOUT_SPEC: &str = "3f2504e0-4f89-41d3-9a0c-0305e82c3301";
const DOC_PLACE_ORDER_CODE: &str = "7c9e6679-7425-40de-944b-e07fc1f90ae7";

/// Build the hardcoded external docs store with made-up links across the
/// three doc systems the linkage needs to support.
fn seed_docs_store() -> DocsStore {
    let mut store = DocsStore::new();
    store.insert(DocObject {
        db_id: 1,
        doc_id: DOC_ARCH_OVERVIEW.to_string(),
        url: "https://confluence.example.com/display/ARCH/Ordering+Platform+Overview".to_string(),
        tags: vec![
            "architecture".to_string(),
            "c4-system".to_string(),
            "overview".to_string(),
        ],
    });
    store.insert(DocObject {
        db_id: 2,
        doc_id: DOC_ORDERING_RUNBOOK.to_string(),
        url: "https://www.notion.so/example/Ordering-Service-Runbook-2b0d7b3dcb6d".to_string(),
        tags: vec![
            "runbook".to_string(),
            "ordering".to_string(),
            "c4-container".to_string(),
        ],
    });
    store.insert(DocObject {
        db_id: 3,
        doc_id: DOC_CHECKOUT_SPEC.to_string(),
        url: "https://github.com/example/ordering/blob/main/docs/checkout.md".to_string(),
        tags: vec![
            "spec".to_string(),
            "checkout".to_string(),
            "c4-component".to_string(),
        ],
    });
    store.insert(DocObject {
        db_id: 4,
        doc_id: DOC_PLACE_ORDER_CODE.to_string(),
        url: "https://github.com/example/ordering/blob/main/docs/place_order.md".to_string(),
        tags: vec![
            "code".to_string(),
            "place-order".to_string(),
            "c4-code".to_string(),
        ],
    });
    store
}

// ---------------------------------------------------------------------------
// Node <-> doc linkage helpers (the abstraction under test)
// ---------------------------------------------------------------------------

/// Property key under which a node carries its external doc UUID links.
const DOC_LINKS_KEY: &str = "doc_links";
/// Property key carrying the node's C4 level tag (system/container/
/// component/code). GridSeak has no native C4-level field today, so the
/// fixture stamps it into the schemaless `properties` bag.
const C4_LEVEL_KEY: &str = "c4_level";

/// Attach external doc UUIDs to a node's metadata.
fn attach_docs(node: &mut Node, doc_ids: &[&str]) {
    let arr = serde_json::Value::Array(
        doc_ids
            .iter()
            .map(|d| serde_json::Value::String((*d).to_string()))
            .collect(),
    );
    node.set_property(DOC_LINKS_KEY, arr);
}

/// Read the external doc UUIDs linked to a node.
fn attached_docs(node: &Node) -> Vec<String> {
    node.properties
        .get(DOC_LINKS_KEY)
        .and_then(|v| v.as_array())
        .map(|a| {
            a.iter()
                .filter_map(|x| x.as_str().map(str::to_string))
                .collect()
        })
        .unwrap_or_default()
}

/// Assert, by inspecting `node.properties` **directly**, that `doc_id`
/// physically resides in the node's metadata. This deliberately does NOT
/// go through `attached_docs`; it reaches into the raw metadata bag so a
/// passing assertion means "the link is stored in the node's metadata",
/// not "a convenience reader happened to return it".
///
/// Verifies three things about the metadata field itself:
/// 1. the `doc_links` key exists in `node.properties`,
/// 2. its value is a JSON array,
/// 3. that array contains the exact `doc_id` string.
fn assert_doc_link_in_metadata(node: &Node, doc_id: &str) {
    let raw = node
        .properties
        .get(DOC_LINKS_KEY)
        .unwrap_or_else(|| panic!("node `{}` metadata has no `{DOC_LINKS_KEY}` key", node.fqn));
    let arr = raw.as_array().unwrap_or_else(|| {
        panic!(
            "`{DOC_LINKS_KEY}` in `{}` metadata is not an array",
            node.fqn
        )
    });
    let present = arr.iter().any(|v| v.as_str() == Some(doc_id));
    assert!(
        present,
        "doc id `{doc_id}` is not present in node `{}` metadata `{DOC_LINKS_KEY}`: {raw}",
        node.fqn
    );
}

/// Construct a C4-tagged container/scaffolding node (FQN-only `id`).
fn c4_node(kind: NodeKind, fqn: &str, level: &str) -> Node {
    let mut n = Node::new(kind, fqn.to_string(), loc(), Provenance::tree_sitter());
    n.set_property(C4_LEVEL_KEY, serde_json::Value::String(level.to_string()));
    n
}

fn loc() -> Range {
    Range::with_file(1, 0, 1, 0, "fixture.rs")
}

/// Rename a node to `new_fqn`, recomputing the content-addressed `id`
/// via the public constructor while preserving `properties` and trait
/// metadata. This is the honest shape of a "relink after rename" step:
/// the id churns, the doc link rides along in `properties`.
fn rename_preserving_metadata(node: &Node, new_fqn: String) -> Node {
    let mut renamed = Node::new(node.kind, new_fqn, node.location.clone(), node.provenance);
    renamed.properties = node.properties.clone();
    renamed.trait_metadata = node.trait_metadata.clone();
    renamed
}

/// Rename every node in the subtree rooted at `old_prefix` (the node
/// whose FQN == `old_prefix`, plus every descendant whose FQN starts
/// with `old_prefix::`) to live under `new_prefix`. Recomputes each
/// node's `id`; preserves each node's `properties`.
fn rename_subtree(graph: &mut Graph, old_prefix: &str, new_prefix: &str) {
    let child_prefix = format!("{old_prefix}::");
    for node in graph.nodes.iter_mut() {
        let is_in_subtree = node.fqn == old_prefix || node.fqn.starts_with(&child_prefix);
        if is_in_subtree {
            let new_fqn = node.fqn.replacen(old_prefix, new_prefix, 1);
            *node = rename_preserving_metadata(node, new_fqn);
        }
    }
}

/// Resolve the doc UUIDs a node inherits, anchored on the **FQN**: the
/// node's own links plus those of every ancestor (every node whose FQN
/// is a prefix of this node's FQN). This is "attach high, inherit low"
/// resolved through the stable FQN anchor — it keeps working after an
/// FQN rename because parent and child FQNs move together.
fn inherited_docs_by_fqn(graph: &Graph, leaf_fqn: &str) -> Vec<String> {
    let mut acc: Vec<String> = Vec::new();
    for node in &graph.nodes {
        let is_ancestor_or_self =
            leaf_fqn == node.fqn || leaf_fqn.starts_with(&format!("{}::", node.fqn));
        if is_ancestor_or_self {
            acc.extend(attached_docs(node));
        }
    }
    acc.sort();
    acc.dedup();
    acc
}

/// id-keyed parent lookup over `Contains` edges. Returns the parent node
/// id, or `None` if the edge set has no `Contains` edge pointing at
/// `child_id` (e.g. because a rename churned the id and the edges went
/// stale before a relink pass ran).
fn contains_parent_id<'a>(graph: &'a Graph, child_id: &str) -> Option<&'a str> {
    graph
        .edges
        .iter()
        .find(|e| e.to_id == child_id && e.kind == EdgeKind::Contains)
        .map(|e| e.from_id.as_str())
}

/// Strip the last `::`-separated segment to get the parent FQN.
fn parent_fqn(fqn: &str) -> Option<String> {
    fqn.rfind("::").map(|i| fqn[..i].to_string())
}

/// Rebuild every `Contains` edge from the FQN hierarchy using the
/// nodes' *current* ids. This is the deterministic relink pass that
/// repairs id-keyed structural edges after an FQN rename churns ids.
fn rebuild_contains_edges(graph: &mut Graph) {
    let id_by_fqn: HashMap<String, String> = graph
        .nodes
        .iter()
        .map(|n| (n.fqn.clone(), n.id.clone()))
        .collect();
    let mut edges = Vec::new();
    for n in &graph.nodes {
        if let Some(pf) = parent_fqn(&n.fqn) {
            if let Some(parent_id) = id_by_fqn.get(&pf) {
                edges.push(Edge::contains(
                    parent_id.clone(),
                    n.id.clone(),
                    Provenance::tree_sitter(),
                ));
            }
        }
    }
    graph.edges = edges;
}

fn node_by_fqn<'a>(graph: &'a Graph, fqn: &str) -> &'a Node {
    graph
        .nodes
        .iter()
        .find(|n| n.fqn == fqn)
        .unwrap_or_else(|| panic!("no node with fqn `{fqn}`"))
}

// ---------------------------------------------------------------------------
// C4 ordering/delivery fixture
// ---------------------------------------------------------------------------

// FQN spine for the model:
//   ordering_platform                                            (L1 System)
//   ordering_platform::ordering_service                          (L2 Container)
//   ordering_platform::ordering_service::checkout                (L3 Component)
//   ordering_platform::ordering_service::checkout::place_order   (L4 Code)
//   ordering_platform::delivery_service                          (L2 Container)
//   ordering_platform::delivery_service::dispatch                (L3 Component)
//   ordering_platform::delivery_service::dispatch::assign_driver (L4 Code)
const SYSTEM_FQN: &str = "ordering_platform";
const ORDERING_FQN: &str = "ordering_platform::ordering_service";
const CHECKOUT_FQN: &str = "ordering_platform::ordering_service::checkout";
const PLACE_ORDER_FQN: &str = "ordering_platform::ordering_service::checkout::place_order";
const DELIVERY_FQN: &str = "ordering_platform::delivery_service";
const DISPATCH_FQN: &str = "ordering_platform::delivery_service::dispatch";
const ASSIGN_DRIVER_FQN: &str = "ordering_platform::delivery_service::dispatch::assign_driver";

/// Build the C4 ordering/delivery graph with docs attached across
/// levels: System → arch overview, ordering Container → runbook,
/// checkout Component → spec, place_order Code → code doc.
fn build_ordering_graph() -> Graph {
    let mut g = Graph::new();

    let mut system = c4_node(NodeKind::Project, SYSTEM_FQN, "system");
    attach_docs(&mut system, &[DOC_ARCH_OVERVIEW]);

    let mut ordering = c4_node(NodeKind::Module, ORDERING_FQN, "container");
    attach_docs(&mut ordering, &[DOC_ORDERING_RUNBOOK]);

    let mut checkout = c4_node(NodeKind::Module, CHECKOUT_FQN, "component");
    attach_docs(&mut checkout, &[DOC_CHECKOUT_SPEC]);

    let mut place_order = c4_node(NodeKind::Function, PLACE_ORDER_FQN, "code");
    attach_docs(&mut place_order, &[DOC_PLACE_ORDER_CODE]);

    let delivery = c4_node(NodeKind::Module, DELIVERY_FQN, "container");
    let dispatch = c4_node(NodeKind::Module, DISPATCH_FQN, "component");
    let assign_driver = c4_node(NodeKind::Function, ASSIGN_DRIVER_FQN, "code");

    for n in [
        system,
        ordering,
        checkout,
        place_order,
        delivery,
        dispatch,
        assign_driver,
    ] {
        g.add_node(n);
    }

    rebuild_contains_edges(&mut g);
    g
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// Sanity: the hardcoded docs store resolves a UUID to its URL + tags.
#[test]
fn hardcoded_docs_store_resolves_uuid_to_link_and_tags() {
    let store = seed_docs_store();

    let doc = store
        .get(DOC_CHECKOUT_SPEC)
        .expect("checkout spec must resolve");
    assert_eq!(doc.db_id, 3);
    assert_eq!(
        doc.url,
        "https://github.com/example/ordering/blob/main/docs/checkout.md"
    );
    assert!(doc.tags.contains(&"checkout".to_string()));

    // An unknown UUID is an explicit miss, not a panic.
    assert!(store.get("00000000-0000-4000-8000-000000000000").is_none());
}

/// Core guarantee: a doc UUID in a node's metadata survives an FQN
/// mutation that churns the content-addressed `id`. The link is intact
/// (same UUID) and still resolves in the docs store afterward.
#[test]
fn doc_uuid_in_metadata_survives_fqn_mutation_with_id_churn() {
    let store = seed_docs_store();

    let mut node = c4_node(NodeKind::Function, PLACE_ORDER_FQN, "code");
    attach_docs(&mut node, &[DOC_PLACE_ORDER_CODE]);

    let id_before = node.id.clone();
    let docs_before = attached_docs(&node);
    assert_eq!(docs_before, vec![DOC_PLACE_ORDER_CODE.to_string()]);

    // The doc id physically lives in the node's metadata bag before mutation.
    assert_doc_link_in_metadata(&node, DOC_PLACE_ORDER_CODE);

    // Mutate the FQN (rename), recomputing the id.
    let renamed = rename_preserving_metadata(
        &node,
        "ordering_platform::ordering_service::checkout::submit_order".to_string(),
    );

    // The id genuinely churned...
    assert_ne!(
        renamed.id, id_before,
        "FQN rename must churn the content-addressed id"
    );
    // ...yet the doc id is STILL inside the node's metadata after mutation.
    // This is the survival assertion, checked against `properties` directly.
    assert_doc_link_in_metadata(&renamed, DOC_PLACE_ORDER_CODE);
    assert_eq!(
        attached_docs(&renamed),
        docs_before,
        "doc link must survive the rename intact"
    );
    assert!(
        store.get(&attached_docs(&renamed)[0]).is_some(),
        "surviving doc link must still resolve in the docs store"
    );
}

/// The deeply-nested case: renaming a mid-tree component cascades FQN
/// changes (and id churn) down to its deeply nested child. Doc links —
/// at every level and on the deep child — must relink: stay intact in
/// metadata, still resolve in the store, and still inherit by FQN
/// anchor. The id-keyed `Contains` edges go stale on rename and are
/// repaired by a deterministic relink pass.
#[test]
fn c4_ordering_system_relinks_after_deeply_nested_child_rename() {
    let store = seed_docs_store();
    let mut g = build_ordering_graph();

    // --- Pre-rename baseline -------------------------------------------------
    let place_order_id_before = node_by_fqn(&g, PLACE_ORDER_FQN).id.clone();
    let place_order_docs_before = attached_docs(node_by_fqn(&g, PLACE_ORDER_FQN));
    assert_eq!(
        place_order_docs_before,
        vec![DOC_PLACE_ORDER_CODE.to_string()]
    );

    // Every level's doc id physically lives in that node's metadata before
    // the rename, including the deeply nested child.
    assert_doc_link_in_metadata(node_by_fqn(&g, SYSTEM_FQN), DOC_ARCH_OVERVIEW);
    assert_doc_link_in_metadata(node_by_fqn(&g, ORDERING_FQN), DOC_ORDERING_RUNBOOK);
    assert_doc_link_in_metadata(node_by_fqn(&g, CHECKOUT_FQN), DOC_CHECKOUT_SPEC);
    assert_doc_link_in_metadata(node_by_fqn(&g, PLACE_ORDER_FQN), DOC_PLACE_ORDER_CODE);

    // The deep child inherits docs from its component, container, and
    // system ancestors via the FQN anchor.
    let inherited_before = inherited_docs_by_fqn(&g, PLACE_ORDER_FQN);
    assert_eq!(
        inherited_before,
        sorted(vec![
            DOC_ARCH_OVERVIEW,
            DOC_ORDERING_RUNBOOK,
            DOC_CHECKOUT_SPEC,
            DOC_PLACE_ORDER_CODE,
        ]),
        "deep child must inherit docs from every ancestor level"
    );

    // id-keyed containment resolves before the rename.
    let checkout_id_before = node_by_fqn(&g, CHECKOUT_FQN).id.clone();
    assert_eq!(
        contains_parent_id(&g, &place_order_id_before),
        Some(checkout_id_before.as_str()),
        "place_order's Contains parent is checkout before rename"
    );

    // --- Mutate: rename the checkout component subtree -----------------------
    // This cascades to the deeply nested child place_order.
    let new_checkout_fqn = "ordering_platform::ordering_service::order_checkout";
    let new_place_order_fqn = "ordering_platform::ordering_service::order_checkout::place_order";
    rename_subtree(&mut g, CHECKOUT_FQN, new_checkout_fqn);

    // --- Post-rename: doc links relink ---------------------------------------
    let place_order_after = node_by_fqn(&g, new_place_order_fqn);

    // The deep child's id churned because its FQN changed.
    assert_ne!(
        place_order_after.id, place_order_id_before,
        "deeply nested child id must churn when its ancestor FQN changes"
    );
    // The doc id is STILL inside the deeply nested child's metadata after the
    // cascading rename, checked against `properties` directly.
    assert_doc_link_in_metadata(place_order_after, DOC_PLACE_ORDER_CODE);
    // The renamed component itself also kept its doc id in metadata.
    assert_doc_link_in_metadata(node_by_fqn(&g, new_checkout_fqn), DOC_CHECKOUT_SPEC);
    // Its doc link is intact and still resolves.
    assert_eq!(
        attached_docs(place_order_after),
        place_order_docs_before,
        "deep child doc link must survive the cascading rename"
    );
    assert!(
        store
            .resolve_all(&attached_docs(place_order_after))
            .iter()
            .all(Option::is_some),
        "deep child doc link must still resolve in the docs store"
    );

    // FQN-anchored inheritance still resolves the full ancestor chain.
    let inherited_after = inherited_docs_by_fqn(&g, new_place_order_fqn);
    assert_eq!(
        inherited_after, inherited_before,
        "inheritance by FQN anchor must relink identically after rename"
    );

    // Every doc link in the whole graph still resolves (nothing orphaned).
    for node in &g.nodes {
        let links = attached_docs(node);
        assert!(
            store.resolve_all(&links).iter().all(Option::is_some),
            "node `{}` has an unresolved (orphaned) doc link: {:?}",
            node.fqn,
            links
        );
    }

    // --- The structural-edge contrast ---------------------------------------
    // id-keyed Contains edges went STALE on rename: the renamed child's
    // new id has no matching edge yet. This is the unlinkage that doc
    // links (anchor-keyed) avoided.
    let place_order_id_after = place_order_after.id.clone();
    assert!(
        contains_parent_id(&g, &place_order_id_after).is_none(),
        "id-keyed Contains edge must be stale after rename (pre-relink)"
    );

    // Relink structural edges deterministically from the FQN anchor.
    rebuild_contains_edges(&mut g);
    let new_checkout_id = node_by_fqn(&g, new_checkout_fqn).id.clone();
    assert_eq!(
        contains_parent_id(&g, &place_order_id_after),
        Some(new_checkout_id.as_str()),
        "Contains edge must relink child to renamed parent after rebuild"
    );
}

fn sorted(v: Vec<&str>) -> Vec<String> {
    let mut out: Vec<String> = v.into_iter().map(str::to_string).collect();
    out.sort();
    out.dedup();
    out
}
