//! Per-ecosystem uncertainty notes for the validation UI.
//!
//! Tells the user what the engine could NOT detect for their language,
//! so they know what to look for during review.

use crate::health::config::Ecosystem;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct EcosystemNote {
    pub category: String,
    pub note: String,
    pub action: String,
}

pub fn generate_ecosystem_notes(ecosystem: Ecosystem) -> Vec<EcosystemNote> {
    let mut notes = Vec::new();

    match ecosystem {
        Ecosystem::Rust => {
            notes.push(EcosystemNote {
                category: "dead_code".into(),
                note: "Macro-generated trait impls (#[derive(Error)], #[tokio::main]) are not detected — macros expand before tree-sitter sees the AST.".into(),
                action: "Review dead code candidates for functions generated by derive macros or proc macros.".into(),
            });
            notes.push(EcosystemNote {
                category: "dead_code".into(),
                note: "Functions passed as closures (e.g., .map(my_func)) may not have incoming call edges.".into(),
                action: "Review candidates that are short utility functions commonly passed as arguments.".into(),
            });
        }
        Ecosystem::Go => {
            notes.push(EcosystemNote {
                category: "dead_code".into(),
                note: "Go interface implementations are detected by name only (ServeHTTP, String, Error, etc.). Custom interface methods with unique names may appear as dead code.".into(),
                action: "Review dead code candidates for functions that implement custom Go interfaces.".into(),
            });
            notes.push(EcosystemNote {
                category: "dead_code".into(),
                note: "init() functions and TestMain are handled, but custom test helpers called only from test files may surface.".into(),
                action: "Confirm that functions only called from *_test.go files are correctly excluded.".into(),
            });
        }
        Ecosystem::Python => {
            notes.push(EcosystemNote {
                category: "dead_code".into(),
                note: "Decorator-invoked functions (@app.route, @pytest.fixture, @property) are plumbed but not yet populated by the parser.".into(),
                action: "Review dead code candidates for decorated functions, especially Flask/Django routes and pytest fixtures.".into(),
            });
            notes.push(EcosystemNote {
                category: "modules".into(),
                note: "Python flat packages (all .py files in one directory) produce a single large module. Consider reviewing module boundaries.".into(),
                action: "If cohesion is very low on a large module, the engine may suggest file-level splitting.".into(),
            });
        }
        Ecosystem::TypeScript | Ecosystem::JavaScript => {
            notes.push(EcosystemNote {
                category: "dead_code".into(),
                note: "Dynamic dispatch (this.method(), obj[key]()) cannot be resolved statically. These calls are captured but the target is unknown.".into(),
                action: "Review dead code candidates in classes with heavy use of 'this' method calls.".into(),
            });
            notes.push(EcosystemNote {
                category: "dead_code".into(),
                note: "JSX component usage (<MyComponent />) is handled, but higher-order components and render props may not resolve correctly.".into(),
                action: "Review candidates that are React components or HOC wrappers.".into(),
            });
        }
        Ecosystem::Java => {
            notes.push(EcosystemNote {
                category: "dead_code".into(),
                note: "Spring annotations (@Bean, @Service, @Component) are plumbed but require parser support to populate is_attribute_invoked.".into(),
                action: "Review dead code candidates for Spring-managed beans and annotated methods.".into(),
            });
        }
        Ecosystem::CSharp => {
            notes.push(EcosystemNote {
                category: "dead_code".into(),
                note: "Unity lifecycle methods (Start, Update, Awake) are handled by name, but custom UnityEvent callbacks may not be detected.".into(),
                action: "Review dead code candidates for Unity MonoBehaviour methods and event handlers.".into(),
            });
        }
        Ecosystem::Apex => {
            notes.push(EcosystemNote {
                category: "dead_code".into(),
                note: "Apex framework entry points (@AuraEnabled, @InvocableMethod, @RestResource, global, webservice, implements Schedulable/Batchable/Queueable, triggers) are classified via the dedicated Apex dead-code reason classifier. Review reason_breakdown.framework_annotation_unresolved before considering any flagged function for removal.".into(),
                action: "Inspect dead code candidates in reason_breakdown: 'no_callers' and 'visibility_private_unused' are delete candidates; 'framework_annotation_unresolved' and 'declarative_wiring_unparsed' are invoked externally.".into(),
            });
        }
        Ecosystem::Unknown => {
            notes.push(EcosystemNote {
                category: "general".into(),
                note: "Ecosystem could not be auto-detected. Generic heuristics are applied, which may be more conservative.".into(),
                action: "Specify the ecosystem explicitly via --ecosystem flag for more accurate analysis.".into(),
            });
        }
    }

    notes
}
